export enum AlertType {
  TRADE_FULFILLED = 'TRADE_FULFILLED',
  STOP_ORDER_PLACED = 'STOP_ORDER_PLACED',
  STOP_ORDER_NOT_PLACED = 'STOP_ORDER_NOT_PLACED',
  WRONG_CURRENCY = 'WRONG_CURRENCY',
  MAXIMUM_DRAWDOWN_EXCEEDED = 'MAXIMUM_DRAWDOWN_EXCEEDED',
  MAXIMUM_POSITION_EXCEEDED = 'MAXIMUM_POSITION_EXCEEDED',
  RISK_POSITION = 'RISK_POSITION',
}
